language : node_js
node_js :
 - stable
install:
 - npm install
script:
 - tsc
 - npm test
deploy:
  provider: npm
  email: stormalinblue@gmail.com
  api_key: $NPM_PUBLISH_TOKEN
  skip-cleanup: true
  on:
    tags: true

